version: '3.5'
services:
  yaml_2_resume:
    container_name: yaml_2_resume
    build: .
    ports:
      - 14567:4567
    working_dir: /usr/src/app
    volumes:
      - ./share:/usr/src/app/share
    # web app mode
    command: ruby app.rb -o 0.0.0.0
    # cmd mode
    # command: ruby make_cv.rb -i templates/academic.yaml -s templates/academic.txt -o share/output.pdf
